# Generated by Django 4.1.7 on 2023-04-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['discipline', 'start_date'], 'verbose_name': 'Занятие (Расписание)', 'verbose_name_plural': 'Занятия (Расписание)'},
        ),
    ]
