# Generated by Django 4.1.7 on 2023-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='max_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_listeners',
            field=models.IntegerField(default=0),
        ),
    ]
