# Generated by Django 4.1.7 on 2023-04-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_lesson_max_applications_lesson_max_listeners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='max_applications',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='max_listeners',
        ),
    ]
