# Generated by Django 4.2 on 2023-05-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_lesson_max_applications_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('student', 'lesson')},
        ),
    ]
