# Generated by Django 4.2 on 2023-05-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_lessonlisteners_applied_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonlisteners',
            name='applied_at',
        ),
    ]
