# Generated by Django 4.2.1 on 2023-06-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='max_listeners',
            field=models.IntegerField(default=0),
        ),
    ]
