# Generated by Django 4.2.1 on 2023-06-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_lesson_max_listeners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
